name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Check Flutter environment
        run: |
          flutter doctor -v
          ls -la ios/Flutter/

      - name: Clean Flutter project
        run: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod deintegrate || true  # لو فيه مشكلة قديمة في الـ Pods
          pod cache clean --all
          pod install --verbose
          ls -la Pods/  # نتأكد إن الملفات اتولدت
          cd ..

      - name: Build iOS app
        run: flutter build ios --release --no-codesign