name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      # ✅ التحقق من أن مجلد iOS موجود
      - name: Check if iOS directory exists
        run: ls -la ios

      # ✅ تنظيف المشروع وإعادة تثبيت الحزم
      - name: Clean and reset iOS project
        run: |
          flutter clean
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.podspec ios/Flutter/Release.xcconfig
          flutter pub get

      # ✅ تثبيت CocoaPods وإنشاء Akar.xcworkspace
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --verbose
          cd ..

      # ✅ تنفيذ البناء
      - run: flutter build ios --release --no-codesign
